#!/usr/bin/env bash

function modify-file {
  sed -i.backup 's/buzz::AsyncSocket/buzz::XmppAsyncSocket/g' "$1"

  sed -i.backup 's/talk_base::/txmpp::/g' "$1"
  sed -i.backup 's/namespace talk_base/namespace txmpp/g' "$1"

  sed -i.backup 's/buzz::/txmpp::/g' "$1"
  sed -i.backup 's/namespace buzz/namespace txmpp/g' "$1"

  sed -i.backup 's/sigslot::/txmpp::/g' "$1"
  sed -i.backup 's/namespace sigslot/namespace txmpp/g' "$1"

  sed -i.backup 's/include "talk/include "txmpp/g' "$1"
}

function convert {
  rm -fr src/txmpp/{base,xmllite,xmpp}

  mkdir -p src/txmpp
  cp -r src/talk/{base,xmllite,xmpp} src/txmpp

  sed -i.backup 's/AsyncSocket/XmppAsyncSocket/g' src/txmpp/xmpp/asyncsocket.h
  sed -i.backup 's/ AsyncSocket/ XmppAsyncSocket/g' src/txmpp/xmpp/*.{cc,h}
  sed -i.backup 's/<AsyncSocket/<XmppAsyncSocket/g' src/txmpp/xmpp/*.{cc,h}

  for path in $( find src/txmpp -name '*.h' -or -name '*.cc' ); do
    modify-file $path
  done
}

function pre-clean {
  find . -name '*.o' -delete
  find . -name '*.os' -delete
}

function post-clean {
  find . -name '*.backup' -delete
}

function fail {
  echo "Unable to setup."
  exit 1
}

cd "$( dirname "$0" )" &>/dev/null || fail

pre-clean && convert && post-clean
